### ISSUE TITLE
TemplateHaskell-generated smart constructors

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#131]
We could relieve some of the tedium of defining new effects by using `TemplateHaskell` to generate smart constructors.

I think this might belong in another package in the org; I kinda like keeping `fused-effects`’ dependencies minimal. Thoughts?

🎩 @isovector for the suggestion.

**Comment by isovector** [comment]
It was pretty trivial to patch [Ed Kmett's implementat](https://raw.githubusercontent.com/ekmett/free/master/src/Control/Monad/Free/TH.hs) to work with my effects, the diff is here if you're interested:

```diff
@@ -38,6 +34,7 @@ import Data.Char (toLower)
 import Data.List ((\\), nub)
 import Language.Haskell.TH
 import Language.Haskell.TH.Syntax
+import Generics.SYB

 #if !(MIN_VERSION_base(4,8,0))
 import Control.Applicative
@@ -191,13 +188,19 @@ extractVars (ParensT x) = extractVars x
 extractVars _ = []

 liftCon' :: Bool -> [TyVarBndr] -> Cxt -> Type -> Type -> [Type] -> Name -> [Type] -> Q [Dec]
-liftCon' typeSig tvbs cx f n ns cn ts = do
+liftCon' typeSig tvbs cx f n nns cn tts = do
   -- prepare some names
   opName <- mkName <$> mkOpName (nameBase cn)
-  m      <- newName "m"
+  r      <- newName "r"
   a      <- newName "a"
-  monadFree <- findTypeOrFail  "MonadFree"
-  liftF     <- findValueOrFail "liftF"
+  semantic <- findTypeOrFail  "Semantic"
+  member   <- findTypeOrFail  "Member"
+  liftF    <- findValueOrFail "send"
+  let m = last nns
+      ns = init nns
+      replaceMType t | t == m = ConT semantic `AppT` VarT r
+                     | otherwise = t
+      ts = everywhere (mkT replaceMType) tts
   -- look at the constructor parameters
   args <- mapM (mkArg n) ts
   let ps = params args    -- these are not using type parameter
@@ -205,26 +208,28 @@ liftCon' typeSig tvbs cx f n ns cn ts = do
   -- based on cs we get return type and refined expressions
   -- (e.g. with Nothing/Just or Left/Right tags)
   (retType, es) <- unifyCaptured a cs
-  -- operation type is (a1 -> a2 -> ... -> aN -> m r)
-  let opType  = foldr (AppT . AppT ArrowT) (AppT (VarT m) retType) ps
+  -- operation type is (a1 -> a2 -> ... -> aN -> Semantic r z)
+  let opType  = foldr (AppT . AppT ArrowT) (ConT semantic `AppT` VarT r `AppT` retType) ps
   -- picking names for the implementation
   xs  <- mapM (const $ newName "p") ps
   let pat  = map VarP xs                      -- this is LHS
       exprs = zipExprs (map VarE xs) es args  -- this is what ctor would be applied to
       fval = foldl AppE (ConE cn) exprs       -- this is RHS without liftF
       ns' = nub (concatMap extractVars ns)
-      q = filter nonNext tvbs ++ map PlainTV (qa ++ m : ns')
+      q = filter nonNext tvbs ++ map PlainTV (qa ++ r : ns')
       qa = case retType of VarT b | a == b -> [a]; _ -> []
       f' = foldl AppT f ns
   return $ concat
     [ if typeSig
 #if MIN_VERSION_template_haskell(2,10,0)
-        then [ SigD opName (ForallT q (cx ++ [ConT monadFree `AppT` f' `AppT` VarT m]) opType) ]
+        then [ SigD opName (ForallT q (cx ++ [ConT member `AppT` f' `AppT` VarT r]) opType) ]
 #else
-        then [ SigD opName (ForallT q (cx ++ [ClassP monadFree [f', VarT m]]) opType) ]
+        then [ SigD opName (ForallT q (cx ++ [ClassP member [f', VarT r]]) opType) ]
 #endif
         else []
-    , [ FunD opName [ Clause pat (NormalB $ AppE (VarE liftF) fval) [] ] ] ]
+    , [ FunD opName [ Clause pat (NormalB $ AppE (VarE liftF) fval) [] ]
+      , PragmaD $ InlineP opName Inline FunLike AllPhases
+      ] ]
   where
     nonNext (PlainTV pn) = VarT pn /= n
     nonNext (KindedTV kn _) = VarT kn /= n
```

**Comment by jkachmar** [comment]
IIRC, `persistent` breaks all of the Template Haskell helpers out into a separate package ([`persistent-template`](http://hackage.haskell.org/package/persistent-template-2.6.0)) to avoid the additional dependency and associated initial compile time hit of the `template-haskell` package.

Seems like that might be a best-of-both-worlds situation, and would be in line with `fused-effects-lens` and `fused-effects-exceptions`, so that people could opt-in for the added convenience.

**Comment by evanrelf** [comment]
Is this something you guys are still interested in?

I'd like to use `fused-effects` for something at work soon, and I'd value having a way to get rid of the smart constructor boilerplate.

I might play around with implementing this in my free time, once the GADT syntax is released in the next version.

**Comment by robrix** [comment]
> Is this something you guys are still interested in?
> 
> I'd like to use `fused-effects` for something at work soon, and I'd value having a way to get rid of the smart constructor boilerplate.
> 
> I might play around with implementing this in my free time, once the GADT syntax is released in the next version.

I think so, tho per @jkachmar’s comment, I’d like to have it live in a separate package, tho perhaps a separate package in this repository.

**Comment by evanrelf** [comment]
> I’d like to have it live in a separate package

Yeah I agree.

**Comment by patrickt** [comment]
Fixed. https://hackage.haskell.org/package/fused-effects-th

**Comment by AlistairB** [comment]
@patrickt FYI, `fused-effects-th` failed for me. The source repo is private, so I couldn't raise the issue I got.

**Comment by patrickt** [comment]
@AlistairB If you can build a reproducible case & file a bug against `fused-effects-th`, I’d be happy to take a look at it.

**Comment by evanrelf** [comment]
@AlistairB The repo seems to have moved from [patrickt/fused-effects-th](https://github.com/patrickt/fused-effects-th) to [fused-effects/fused-effects-th](https://github.com/fused-effects/fused-effects-th), but @patrickt that isn't reflected on Hackage.

**Comment by patrickt** [comment]
@evanrelf Good catch. Updating.

**Comment by AlistairB** [comment]
Ah thanks. Created https://github.com/fused-effects/fused-effects-th/issues/1
