### ISSUE TITLE
Define a zero-boilerplate generic carrier

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#132]
We can define a zero-boilerplate carrier parameterized by an effect handler (basically a function suitable for defining `eff`) as a super simple way to define semantics inline before graduating to a “real” carrier if/when you need more efficiency.

I rejected this idea in an earlier iteration due to overestimating the tolerability of the carrier boilerplate for some users. Now, however, @isovector has persuaded me that this is a useful stepping stone.

Here’s my initial stab at it:

```haskell
runInterpret :: (forall x . eff m (m x) -> m x) -> InterpretC eff m a -> m a
runInterpret handler = runReader (Handler  handler) . runInterpretC

newtype InterpretC eff m a = InterpretC { runInterpretC :: ReaderC (Handler eff m) m a }
  deriving (Applicative, Functor, Monad)

instance MonadTrans (InterpretC eff) where
  lift = InterpretC . lift

newtype Handler eff m = Handler (forall x . eff m (m x) -> m x)

runHandler :: HFunctor eff => Handler eff m -> eff (InterpretC eff m) (InterpretC eff m a) -> m a
runHandler h@(Handler handler) = handler . handlePure (runReader h . runInterpretC)

instance (HFunctor eff, Carrier sig m) => Carrier (eff :+: sig) (InterpretC eff m) where
  eff (L op) = do
    handler <- InterpretC ask
    lift (runHandler handler op)
  eff (R other) = InterpretC (eff (R (handleCoercible other)))
```

and here’s it in action:

```
λ run (runInterpret (\case { Get k -> k 5 ; Put _ k -> k }) get) :: Integer
5
```

🎩 suggested by @isovector.

**Comment by robrix** [comment]
@joshvera indicated he was on board with this.

@joshvera @patrickt: What do we think about doing this for the 0.3 release vs. pushing it to a minor version (e.g. 0.3.1)?

**Comment by robrix** [comment]
I’m super curious whether we can implement something analogous which carries state along with it.

**Comment by robrix** [comment]
If we do this, we should also benchmark `runInterpret` for an effect like `State` against a carrier like `StateC`.

**Comment by joshvera** [comment]
> What do we think about doing this for the 0.3 release vs. pushing it to a minor version (e.g. 0.3.1)?

I'm partial to a 0.3 minor release as per [semver](https://semver.org). I believe semver would consider a 0.3.1 a patch release. If we run out of minor release numbers we can run to the number store and order some more.

**Comment by robrix** [comment]
Same as #133, we’re [under PVP rather than semver](
https://github.com/fused-effects/fused-effects/issues/133#issuecomment-474905358). So 0.3.1 would be a minor release.

> If we run out of minor release numbers we can run to the number store and order some more!

😂

**Comment by robrix** [comment]
After discussion w/ @joshvera, we’ve decided to ship this in 0.3.1 rather than holding up 0.3 waiting on it.

**Comment by isovector** [comment]
This looks super similar to [my effect type](https://github.com/isovector/polysemy/blob/546cf16e1b2146326e8e2908847c75c5c82b41e6/src/Polysemy.hs#L26-L32)

```haskell
newtype Semantic r a = Semantic
  { runSemantic
        :: ∀ m
         . Monad m
        => (∀ x. Union r (Semantic r) x -> m x)
        -> m a
  }
```

If it works, this I think would be the stepping stone between our effects implementations. You guys might be putting me out of business here!

**Comment by isovector** [comment]
The trick for doing statefulness is to [just let `m` be `StateT s n`](https://github.com/isovector/polysemy/blob/546cf16e1b2146326e8e2908847c75c5c82b41e6/src/Polysemy/Effect/New.hs#L44-L58)
