### ISSUE TITLE
Define a zero-boilerplate generic interposition/eavesdropping carrier

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#133]
Similar to #132’s proposed zero-boilerplate carrier for effects, we can define a zero-boilerplate interposition carrier for effects, allowing you to intercept and possibly respond to requests for other effects.

I’ve been adamantly opposed to adding other definitions of interposition which we’ve made, due to some of the egregious hacks they required, but this stab at it seems to work nicely while avoiding any such hackery:

```haskell
runInterpose :: (forall x . eff m (m x) -> m x) -> InterposeC eff m a -> m a
runInterpose handler = runReader (Handler handler) . runInterposeC

newtype InterposeC eff m a = InterposeC { runInterposeC :: ReaderC (Handler eff m) m a }
  deriving (Applicative, Functor, Monad)

instance MonadTrans (InterposeC eff) where
  lift = InterposeC . lift

newtype Handler eff m = Handler (forall x . eff m (m x) -> m x)

runHandler :: HFunctor eff => Handler eff m -> eff (ReaderC (Handler eff m) m) (ReaderC (Handler eff m) m a) -> m a
runHandler h@(Handler handler) = handler . handlePure (runReader h)

instance (HFunctor eff, Carrier sig m, Member eff sig) => Carrier sig (InterposeC eff m) where
  eff (op :: sig (InterposeC eff m) (InterposeC eff m a))
    | Just (op' :: eff (InterposeC eff m) (InterposeC eff m a)) <- prj op = do
      handler <- InterposeC ask
      lift (runHandler handler (handleCoercible op'))
    | otherwise = InterposeC (ReaderC (\ handler -> eff (handlePure (runReader handler . runInterposeC) op)))
```

Here’s a use of it to eavesdrop on requests for a `State` effect while still using the underlying `StateC` to respond:

```
λ runM (runState 5 (runInterpose @(State Integer) (\ op -> liftIO (putStrLn "state op") *> send op) get)) :: IO (Integer, Integer)
state op
( 5 , 5 )
```

And here’s a use of it to intercept and respond to requests for a `State` effect without involving the underlying `StateC` at all:

```
λ runM (runState 5 (runInterpose @(State Integer) (\case { Get k -> k 42 ; Put _ k -> k }) get)) :: IO (Integer, Integer)
( 5 , 42 )
```

This would supersede #6 (because we’d document this carrier itself).

**Comment by robrix** [comment]
cc @isovector, since I think this might be relevant to your efforts.

**Comment by robrix** [comment]
@joshvera @patrickt: What do we think about doing this for the 0.3 release vs. pushing it to a minor version (e.g. 0.3.1)?

**Comment by robrix** [comment]
I’m super curious whether we can implement something analogous which carries state along with it.

**Comment by joshvera** [comment]
> What do we think about doing this for the 0.3 release vs. pushing it to a minor version (e.g. 0.3.1)?

I am partial to a 0.3 minor release for new features as per [semver](https://semver.org) and 0.3.1 might be considered a patch release in that sense.

**Comment by robrix** [comment]
@joshvera: `fused-effects` is under PVP rather than semver; it’s mostly the same, but the first two numbers are both major releases, and there’s no special meaning for `0.*`. So the in-progress 0.3 release is a major one, 0.3.1 would be minor, and 0.3.1.1 would be a patch.

**Comment by robrix** [comment]
After discussion w/ @joshvera, we’ve decided to ship this in 0.3.1 rather than holding up 0.3 waiting on it.
