### ISSUE TITLE
Implement generalized unlift functionality a la MonadBaseControl.

### ISSUE THREAD

**Issue by patrickt** [fused-effects/fused-effects#148]
Right now it’s possible to implement an ad-hoc version of an `unlift` function by creating an effect that takes an `m a -> IO a` function and carries it around in a `Handler`. This pattern is somewhat clumsy, as composing these unlift functions is really fiddly and requires O(n) adjustments when you add a new one.

Now that carriers are monads, we should be able to implement something along the lines of `MonadBaseControl`, using a type family to preserve an effect’s state type.

**Comment by mitchellwrosen** [comment]
I'm excited for this, I assume it would lay the groundwork for a convenient `Async` effect?

**Comment by robrix** [comment]
@mitchellwrosen: probably it’d underlie that, `bracket`, catching of exceptions in `IO`, maybe even `mask`… Pretty handy stuff.

**Comment by patrickt** [comment]
This has been addressed with #159 and [`fused-effects-control`](https://github.com/fused-effects/fused-effects-control).
