### ISSUE TITLE
Effect’s laws are undocumented

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#160]
I _think_ `hmap`’s behaviour is guaranteed by parametricity, but `handle` needs to be a well-behaved distributive law, and we should document that fact.

**Comment by mitchellwrosen** [comment]
Random question, why is `handle` named such? It's `weave` in the paper, and `handle` conflicts with `Control.Exception.handle` (tho I always use `catch` anyway)

**Comment by robrix** [comment]
It’s from _Effect Handlers in Scope_, where they named it `handle`; its job is to apply a handler (expressed as a distributive law) to any higher-order positions within the effect.

**Comment by mitchellwrosen** [comment]
I may be looking at the wrong version of the paper, but http://www.cs.ox.ac.uk/people/nicolas.wu/papers/Scope.pdf defines:

```
weave ::(Monad m,Monad n,Functor s) ⇒
s () → Handler s m n → (sig m a → sig n (s a))
```

**Comment by robrix** [comment]
Ah! The version I have names that `handle` and doesn’t introduce the `Handler` synonym 😊

**Comment by robrix** [comment]
In any case, we’ve departed from the names used in the literature in several cases (e.g. `Carrier` instead of `TermAlgebra`/`TermMonad`, `eff` instead of `con`, `Effect` instead of `Syntax`, etc.) where we felt our choice of names would be clearer; I’m not married to any particular selection of names here, tho, and we can always reconsider.

**Comment by robrix** [comment]
A couple of updates:

1. `HFunctor` is gone 🔥

2. We now document the laws for the handler passed to `thread`.

**Comment by patrickt** [comment]
Can we close this?

**Comment by robrix** [comment]
Nope, as discussed in #296, we haven’t figured out what the laws are yet.

**Comment by robrix** [comment]
Closing this as `Effect` is gone as of #361.
