### ISSUE TITLE
Add example of reinterpreting/selectively discharging effects

### ISSUE THREAD

**Issue by jkachmar** [fused-effects/fused-effects#168]
I'm currently riffing of @mitchellwrosen's `servant-client` effect in an attempt to better understand how to use `fused-effects` a bit better and I'm running into something that I'm not quite sure how to work around.

([I've put my code up in a gist, for reference.](https://gist.github.com/jkachmar/a94eb8421f1eafd3e4a7400d509e84ce#file-effhttprequest-hs))

---

In short, I'm trying to figure out how I can discharge one of the effect constraints in a computation (namely I'd like to turn `(Carrier sig m, Member (Error Servant.ClientError) m) => m a` into `m (Either Servant.ClientError a)`).

When I try to use `Control.Effect.Error` to express my errors and then discharge them with via `runError`, I incur an `Effect sig` constraint (presumably because `fused-effects` needs _something_ to discharge the constraint into). Intuitively I felt like I could use `ErrorC` directly to do this, but that hasn't really panned out.

However when I reach for `ExceptT` (which is more familiar to me) I find that everything works out quite nicely (cf. the gist).

So I _feel_ like this is a thing that should be possible, either by using a concrete carrier to discharge a single effect in a stack of effects **or** by reinterpret a stack of effect constraints into another stack of effect constraints; unfortunately I've got no idea how to go about it 😅 .

**Comment by mitchellwrosen** [comment]
Hm, I've read over this a couple times and I don't totally follow :sweat_smile: - but I have this `HttpRequestEffect` around that I think I understand. I can try to help you over the phone 831-247-0026

**Comment by jkachmar** [comment]
Given that I can do the following with `mtl`:
```
λ> f :: (MonadState Int m, MonadError String m) => m (); f = throwError "Hello"
λ> :t runExceptT f
runExceptT f :: MonadState Int m => m (Either String ())
```
...can I do something similar with `fused-effects`? 
e.g.:
```
λ> f :: (Carrier sig m, Member (State Int) sig, Member (Error String) sig) => m (); f = throwError @String "Hello"
λ> :t runError f
runError f :: (Carrier sig, Member (State Int) sig) => m (Either String ())
```

I think the answer is not without the result incurring an `Effect sig` constraint (`runError f :: (Effect sig, Carrier sig, Member (State Int) sig) => m (Either String ())`, and I haven't seen other examples with `Effect sig` so I'm unsure of the implications of incurring that constraint.

**Comment by patrickt** [comment]
@jkachmar The `Effect sig` constraint is benign. It is there (I believe) to handle the threading of effects through suspended state. Your example looks good to me!

**Comment by jkachmar** [comment]
Makes sense, thanks @patrickt @mitchellwrosen!

**Comment by robrix** [comment]
As @patrickt noted, you need an `Effect` constraint to run effects like `Error` and `State` that modify the result type in some fashion (e.g. wrapping it in a functor), but not e.g. `Reader`. The `Effect` constraint is required by the `Carrier` instances for e.g. `ErrorC` & `StateC`, and so adding it is correct.
