### ISSUE TITLE
[Question/Commentary] Implementing a carrier as a newtype over multiple primitive effects?

### ISSUE THREAD

**Issue by mitchellwrosen** [fused-effects/fused-effects#177]
Hi folks, I recently came across a small issue with using fused-effects and was wondering what the idiomatic solution might be.

First, some background - defining a carrier over a single, primitive effect requires only a small amount of boilerplate. It typically looks like this:

```haskell
newtype MyC m a = MyC (StateC S m a)

instance Carrier sig m => Carrier (MyE :+: sig) (MyC m) where
  eff (L sig) = ...

  eff (R other) = MyC (eff (R (handleCoercible other)))
```

This `MyC (eff (R (handleCoercible other)))` is the most painful and confusing part, but I am basically able to recall it from memory now.

Now, onto the issue. I recently implemented a carrier over separate `StateC` and `WriterC` layers:

```haskell
newtype MyC m a = MyC (StateC S (WriterC W m) a)
```

I was unable to figure out how to cleanly implement the `eff (R other)` case as above. Instead, I had to manually call `handle`, which I feel is unfortunate, as it's complex, and was already written once in `StateC`/`WriterC`s' carrier instances. Here is what I ended up with:

```haskell
eff (R other) =
  MyC $
    StateC $ \s ->
      eff (R (handle (s, ()) (\(s, m) -> runStateC m x) (handleCoercible other)
```

It left me feeling averse to add more layers to my carrier, as the complexity of this function would keep growing.

There's another option altogether, which is to define the carrier over just `m a`, but include `Member` constraints in the instance context for the primitive effects I want:

```haskell
newtype MyC m a = MyC (m a)

instance (Carrier sig m, Member (State S) sig, Member (Writer W) sig) 
    => Carrier (MyE :+: sig) (MyC m) where
```

Then, in the "run" function, I can satisfy the `Member` requirements myself:

```haskell
runMyE :: Carrier sig m => MyC (StateC S (WriterC W m)) a -> m a
runMyE (MyC m) = ...
```

but the problem here is that my internal carrier details are leaking out a bit. The outside world does not need to know about `S` and `W`, and even worse, I've prevented the rest of the stack from using unrelated `State S` and `Writer W` layers. This can be worked around by making `S` and `W` abstract types, but that feels fragile as one might not realize the purpose of the newtypes and accidentally refactor them away.

**Comment by patrickt** [comment]
You’re definitely on the right track: `newtype`s over existing carriers is the idiomatic way to compose primitive effects into a unified one. As far as your example of multiple composed carriers, we do this in the teletype example:

```haskell
newtype TeletypeRetC m a = TeletypeRetC { runTeletypeRetC :: StateC [String] (WriterC [String] m) a }
  deriving newtype (Applicative, Functor, Monad)

instance (Carrier sig m, Effect sig) => Carrier (Teletype :+: sig) (TeletypeRetC m) where
  eff (R other)       = TeletypeRetC (eff (R (R (handleCoercible other))))
  -- elided
```

Note the two `R` values: you have to put as many `R` constructors as there are layers of carriers. See the [`Naming` effect](https://github.com/github/semantic/blob/master/semantic-core/src/Data/Name.hs#L121) for another example of this.

I agree that this idiom is not well-handled in our current approach. I’m not sure what an easier API would look like for this, or whether it would even be possible given our type constraints. At some point, you have to stick enough `R` values in there to make carrier matching work. @robrix, do you have any thoughts?

**Comment by mitchellwrosen** [comment]
Yay! Of course. Thanks for the pointer.

**Comment by robrix** [comment]
@patrickt: I’m personally pretty happy with that approach for compositional, implementation-hiding carriers, but maybe we should document it better? cf #135

**Comment by patrickt** [comment]
@robrix I agree. Since it looks like @mitchellwrosen’s question has been answered, I’m gonna close this in favor of #135.
