### ISSUE TITLE
Another Resource effect?

### ISSUE THREAD

**Issue by mitchellwrosen** [fused-effects/fused-effects#179]
I believe the `ResourceT` way of allocating resources is necessary for certain use cases, like streaming.

An example: consider spawning a process and reading its stdout as a stream of lines. The cleanup action here `waitpid`s. With a `ResourceT`-style effect, we can `lift` the allocation into the `Stream` monad.

```haskell
-- Resource effect smart constructor
allocate 
  :: (Carrier sig m, Member Res sig) 
  => IO a 
  -> (a -> IO ()) 
  -> m (ReleaseKey, a) 

-- Stream lines from OS process
spawnThing 
  :: (Carrier sig m, Member Res sig) 
  => String 
  -> Stream (Of String) m ExitCode
```

However, with `bracket`-style allocation, where the resource is only alive in the context of a callback function, I think you'd have trouble writing `spawnThing` with that type. CPS might work but it is more difficult to work with:

```haskell
spawnThing
  :: (Carrier sig m, Member Resource sig)
  => String
  -> (Stream (Of String) m ExitCode -> m r)
  -> m r
```

**Comment by patrickt** [comment]
I’ve actually wanted this in the past specifically for streaming use cases. I would like to see this, and might take a stab at it, possibly in a `fused-effects-streaming` package so that we can provide a really good interface for streaming-style tasks.
