### ISSUE TITLE
Surprising interaction with State + Resource

### ISSUE THREAD

**Issue by ocharles** [fused-effects/fused-effects#180]
What would you guess would be the behavior of the following problem?

```haskell
do
  put 'A'
  bracket
    (get @Char >>= liftIO . print)
    (const (get @Char >>= liftIO . print))
    (const (get @Char >>= liftIO . print))))))                            
```

If you guessed that `A` would be printed at least once, you'd be making a perfectly reasonable guess, but of course, the answer is the much more fun "well, it depends". In particular, it depends on what interpretation you want to give `State` and `Resource`. But let's take two perfectly reasonable interpretations: `runState` and `runResource`:

```haskell
void . runM . runState '?' . runResource (runM . fmap snd . runState '?')
  :: Control.Effect.Internal.Eff
       (ResourceC
          (Control.Effect.Internal.Eff
             (StateC Char (Control.Effect.Internal.Eff (LiftC IO)))))
       a
     -> IO ()
```

Looks pretty legit to me! If we give this interpreter our program, we get (what I consider to be) a very surprising out:

```
'?'
'?'
'?'
```

If I take a bit of time, I can explain what's happening - `Control.Exception.bracket` needs an `IO` argument in the acquire/release/use phases, but we have a much more general `State` computation. So our only option is to run this state down to `IO` in each argument. The surprising behavior is that this state-running comes from the argument to `runResource` which knows nothing about the state at the point `bracket` is called.

`withResource` does not suffer from this problem because it uses `MonadUnliftIO` and thus there is no concept of "state at the point `bracket` is called" (at least, not in the terms of internal monadic state).

**Comment by ocharles** [comment]
My issue is a bit unfair, there's not really anything you can do about this, it's a fairly fundamental problem. But it may be worth documenting that `runResource` is super dodgy, and `withResource` is likely to be much more intuitive.

**Comment by robrix** [comment]
@ocharles: Thanks so much for filing! This is a superb issue ✨

Fundamental or not, I’ve labelled it as a bug if only for the docs you describe.

We’ve talked a bit about trying to suspend/resume e.g. `State` effects (it’s not dissimilar to how higher-order effects work, really) for things like `runResource`; that way, rather than having two calls to `runState` (one outside and one in its argument), you’d only have the one outside of `runResource`, and it would do the right thing inside, automatically. But we haven’t really explored that just yet.

**Comment by ocharles** [comment]
Excellent! And for full disclosure, this "bug" comes from my work in trying to explore similar things in `polysemy` - https://github.com/polysemy-research/polysemy/issues/80 has plenty of rambling, but it's somewhat tangential to this issue. Basically, I've reached a point where we too have the same bug as you :sweat_smile:

**Comment by isovector** [comment]
I've got a partial solution to this problem that I'm planning on merging in polysemy. I'm not sure whether you can take advantage of the technique, but I'll sketch the idea here. There is a full implementation in https://github.com/polysemy-research/polysemy/pull/126.

1. Add a new interpreter with the type `LastMember (Lift IO) r => Sem (Resource ': r) a -> Sem r a` --- note there is no natural transformation.
2. Interpret `bracket` by forking a new thread and running the to-be-bracketed code there
3. Implement the `Sem r ~> IO` transformation by message-passing all of the effects from the new thread back to the main thread. But run IO effects directly on the new thread.
4. While `bracket` is running, switch the main thread into a event-loop, whose only job is to respond to the worked thread.

The implementation is admittedly pretty gross and I'd love a better way to do it, but it buys some pretty good semantics. It means you can get a consistent view of any effects that run after `Resource`. Such a thing extends the intuition that `runError . runState` has local state, but `runState . runError` has global state.

That being said, it extends this same intuition to bracket-safety. Namely that `runBracket . runErrorAsExc` is bracket-safe, but `runErrorAsExc . runBracket` is not. 

The same trick can be used for globally threading `State` throughout a program underneath an `Async` effect. It's not perfect, but it seems like a good practical compromise.

**Comment by ocharles** [comment]
Note that the above is also known as the "fork-lift pattern": https://apfelmus.nfshost.com/blog/2012/06/07-forklift.html

**Comment by isovector** [comment]
Just when I think I've come up with something brilliant, it's already been done! Thanks for the pointer, Ollie, I'll dig in!

**Comment by patrickt** [comment]
I wonder whether we shouldn’t just nix runResource? Given that there’s really only one valid unlifter function, I’m in favor of removing footguns.

**Comment by robrix** [comment]
@patrickt: :+1: agreed

**Comment by ocharles** [comment]
My preference is to remove footguns for as long as they exist, yea. If a viable alternative comes out, great! But in the meantime I don't think there's any reasonable way of exposing this function (other documenting it with "psst, only use me if you have `Reader` underneith!)

**Comment by patrickt** [comment]
Okay, I'll remove the old `runResource` function and rename `withResource` to `runResource`.
