### ISSUE TITLE
Brainstorming an approach using reflection

### ISSUE THREAD

**Issue by ocharles** [fused-effects/fused-effects#191]
Hello friends! I've recently been looking at doing what `fused-effects` does, but without all the `newtype`s and `instance`s that are required from a user. To recap, if I want to write an `Error` effect, I have to define:

1. The GADT
2. An `Effect` instance
3. A carrier newtype
4. A `Carrier` instance

Oh my - what a lot of work!

After a *lot* of studying, I've found out that the approach in `fused-effects` is so damn fast *because* so much is passed around through type classes and not a typical reader monad. However, we know how to bring type classes into scope at runtime, and that's by the magic of `reflection`.

In [this](https://gist.github.com/ocharles/0ede5507e39315253db0782e01acb8f6) Gist, I've rebuilt the `Error` effect but using my `reflection` formulation. As you can see, the core is beautifully efficient - literally everything has inlined. This means a user effect is reduced to:

1. The GADT
2. An `Effect` instance
3. A call to `interpretT`, which interprets the effect through some fundamental monad transformer.

Do you have any thoughts on this? On the one hand, it could replace the `Interpret` module, it could be another module, but it could also be used as the main approach throughout the entire library.

The only drawback I'm aware of is GHC sucks at composing higher-rank functions with `.`, so users would have to use `$` or explicit application. This only sucks at the point where you apply interpreters, which is a very small part of using effects.

**Comment by ocharles** [comment]
I see @mitchellwrosen has also explored something like this in https://github.com/fused-effects/fused-effects/issues/57, but I think my work is taking this to its logical conclusion.

**Comment by ocharles** [comment]
Sorry for the spam, but @isocvector this may interest you too. I believe using `reflection` is the only way to get performance on par with `fused-effects` because it means all functions become fully inlineable as they aren't recursive. `loop-breaker` is getting you *some* inlining, but not as much as what is possible with this/`fused-effects`. May be food for thought for `polysemy`.

**Comment by robrix** [comment]
I haven’t had a chance to do more than skim just yet, but this is super exciting! I especially like how you’ve captured `Transformer`—this has the potential to pay dividends throughout the lib, IMO.

I’d be super interested to see what this would look like as a replacement for the `Interpret` module, and ideally using that as a staging area for exploring this as our primary approach. Would you be open to submitting a PR? I’d be especially keen on learning more about how it compares with our current approach for deeper stacks of effects in terms of the generated Core, benchmarks, ergonomics, etc. ✨

**Comment by robrix** [comment]
> After a _lot_ of studying, I've found out that the approach in `fused-effects` is so damn fast _because_ so much is passed around through type classes and not a typical reader monad.

This is probably a good opportunity for documentation on our part 😅

**Comment by ocharles** [comment]
Thanks for the feedback!

> I’d be super interested to see what this would look like as a replacement for the Interpret module

Indeed, that's probably the best place for this to go next. I can look into crafting a PR. It would be nice to remove some of my machinery in favour of yours (e.g., `Carrier`, `Effect`, sum of functors, etc).

> I’d be especially keen on learning more about how it compares with our current approach for deeper stacks of effects in terms of the generated Core, benchmarks, ergonomics, etc. 

Yes, me too! I took your benchmarks and ran it against my library, the timing is identical... but the benchmarks don't really benchmark much!

**Comment by robrix** [comment]
> Yes, me too! I took your benchmarks and ran it against my library, the timing is identical... but the benchmarks don't really benchmark much!

💯, maybe we should try benchmarking against a more significant workload (e.g. something involving `semantic`).

**Comment by ocharles** [comment]
I've invited you to a project I started a while ago called `effect-zoo` which was trying to build a comprehensive set of benchmarks, maybe take a look at that if you get any free time.

**Comment by robrix** [comment]
Implemented in #193.
