### ISSUE TITLE
Should we re-export Lift, LiftC, PureC, & runM from the carrier modules?

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#214]
We re-export `Pure` & `run` from all of the carrier modules ever since #192, but if you want to terminate your effect stack with another monad then you have to import `Control.Effect.Lift` (🔜 `Control.Carrier.Lift`).

- Should we re-export `Lift` & `runM` from carrier modules as well?
- What about `sendM`?

**Comment by robrix** [comment]
Correction: we do not re-export `Pure` (which would be pointless) or `PureC` (which we probably should).

**Comment by robrix** [comment]
Amended the title to list everything we might want to re-export.

**Comment by robrix** [comment]
@patrickt: Would love to get your opinions on this. For the moment I’m kinda leaning towards “meh,” especially given that we’ve got a `Carrier` instance for `IO` now.

**Comment by patrickt** [comment]
I agree; I don’t think it’s worth the overhead that it would entail in the docs, especially given our more convenient Carrier instances. I vote we close this.
