### ISSUE TITLE
Defining carrier types is tedious

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#215]
Carrier types are a lot more involved than just `Carrier` instances: we require `Functor`, `Applicative`, and `Monad` instances due to `Carrier`’s superclasses, but we typically ship carrier types with a large number of other instances as well:

- `Alternative`
- `MonadFail`
- `MonadFix`
- `MonadIO`
- `MonadPlus`
- `MonadTrans`
- sometimes, `MonadUnliftIO`

Sure, `MonadFail` and `MonadIO` can usually be implemented conveniently using `MonadTrans`. Sure, `MonadPlus` doesn’t require any implementation beyond what’s already in `Alternative` + `Monad`. Sure, not everything requires (or supports) `MonadUnliftIO`.

It’s still a lot of boilerplate, and users might assume that they need to provide it as well. Plus, `Alternative`, `MonadFail`, `MonadIO`, and `MonadPlus` are all duplicative of effects (to wit, `Choose`, `Empty`, `Fail`, and `Lift`).

We moved away from always representing effects in `Codensity` for performance and convenience reasons, but one thing it had going for it was that having a single outermost type which users interacted with meant that we only needed to provide these instances once, and could define them in terms of the effects.

It seems reasonable that `NonDetC` should have an `Alternative` instance in addition to its `Carrier` instance, since that means it could be used (via `Alternative`) without effects; could be handy in a corner, no reason not to. But the choices here get a lot weirder when it comes to `EmptyC`—currently it defines an `Alternative` instance via `Maybe`’s. But should it also define a `MonadFail` instance locally (instead of by passing it on to its underlying monad)? What about `ErrorC String`? Should _it_ have an `Alternative` instance?

If we had a top-level `newtype`—essentially the identity monad transformer—with instances defined using `Carrier`, then many of these instances can go away altogether: there’s no reason for `StateC` to provide `Alternative` or `MonadFail` instances, because if you want to use `Alternative` as an interface to `NonDet` or `MonadFail` as an interface to `Fail`, then that’s arranged for via this top-level `Eff` type. In fact, _none_ of the carriers would need these instances; only `Eff` would.

There is some weirdness associated with this:

- `MonadIO` would probably require some `LastMember` counterpart to `Member` to allow for `(MonadIO m, LastMember (Lift m) sig, Carrier sig m) => MonadIO (Eff m)` instead of the much more restrictive `(Member (Lift IO) sig, Carrier sig m) => MonadIO (Eff m)` we’d otherwise be limited to.
- The type signature of every function would have to change again 😭
- We’d probably want to have `Eff` only occur at the outermost (instead of wrapping every intermediate carrier), but that makes handlers slightly inconvenient to write.

**Comment by robrix** [comment]
#306 improves things by obviating the need for `MonadUnliftIO` and even `MonadIO` (tho you might want the latter still).

Ultimately I think this issue boils down to “_n²_ instances is a problem” which we already knew and which this library is already addressing. End users need only define the interfaces they actually use, and will generally be doing so by wrapping or composing other carriers, and thus I think this isn’t actually a problem we need to solve ourselves.

**Comment by patrickt** [comment]
Agreed.
