### ISSUE TITLE
Many handlers are redundant with record selectors

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#232]
We’ve been defining separate record selectors & handler functions for a long time, e.g.:

```haskell
run :: PureC a -> a
run = runPureC

newtype PureC a = PureC { runPureC :: a }

runError :: ErrorC exc m a -> m (Either exc a)
runError = runErrorC

newtype ErrorC e m a = ErrorC { runErrorC :: m (Either e a) }
```

These definitions are pretty redundant, and we could really abbreviate them by renaming the selectors:

```haskell
newtype PureC a = PureC { run :: a }

newtype ErrorC e m a = ErrorC { runError :: m (Either e a) }
```

The only downside is that haddock makes the type of `runError` in the first case much more obvious than in the second.

**Comment by robrix** [comment]
NB: We still wouldn’t want to do this for selectors taking arguments, e.g. `runReaderC`/`runStateC`, since the flipped operand order is important.

**Comment by ocharles** [comment]
> The only downside is that haddock makes the type of runError in the first case much more obvious than in the second.

Is this true if you export outside the data type? E.g.,

```haskell
module Foo ( Foo, runFoo ) where

newtype Foo m a = Foo { runFoo :: m a }
```

**Comment by robrix** [comment]
Good question! Definitely worth checking.

**Comment by robrix** [comment]
@ocharles: perfect!

<img width="349" alt="Screen Shot 2019-10-08 at 11 16 18 PM" src="https://user-images.githubusercontent.com/59671/66449064-c1ef0c00-ea21-11e9-9e9d-2c1b3627a0dd.png">

Thank you very much 😊

**Comment by ocharles** [comment]
The only thing that still sucks is you can *technically* still do:

```haskell
foo :: ThrowC e m a
bar = foo { runThrow = return () }
```

Which is super weird, but the Haddock's don't really suggest that, so it would just be somebody knowing the internals.

But that's very niche - I think this looks good! :+1:
