### ISSUE TITLE
What should the idiom for delegating the tail of the signature be?

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#235]
`Carrier` instances often delegate the tail of the signature to the underlying carrier:

```haskell
newtype FooC m a = FooC { runFooC :: m a }

instance Carrier sig m => Carrier (Foo :+: sig) (FooC m) where
  eff (L …)     = …
  eff (R other) = FooC (eff (handleCoercible other))
```

when `FooC` is defined as a composition of other carriers, then this often also involves supplying a number of `R`s corresponding to the number of effects handled by the carriers it wraps:

```haskell
newtype FooC m a = FooC { runFooC :: ReaderC Int m a }

instance Carrier sig m => Carrier (Foo :+: sig) (FooC m) where
  eff (L …)     = …
  eff (R other) = FooC (eff (R (handleCoercible other)))
```

```haskell
newtype FooC m a = FooC { runFooC :: ReaderC Int (StateC String m) a }

instance Carrier sig m => Carrier (Foo :+: sig) (FooC m) where
  eff (L …)     = …
  eff (R other) = FooC (eff (R (R (handleCoercible other))))
```

and so on.

It turns out that `send` handles all of these uniformly: `send = alg . inj`, and `inj` abstracts over sums all the way up to a reflexive instance. This raises a few questions:

- What are the tradeoffs of using `send` vs. `eff` & some composition of `R`s? For example:
  - Is it ever ambiguous?
  - Does it harm inference?
  - Is it clearer as to the intent, or is it too magical?
  - Is it actually more convenient in practice?
  - Does it perform differently?
- Based on the above, should we change the default idiom used & documented in `fused-effects`?

**Comment by robrix** [comment]
Anecdotally, counting how many `R`s should be used is hella tedious, especially when changing the definition of the carrier to add or remove encapsulated carriers.

**Comment by patrickt** [comment]
FWIW, I think it’s a little clearer what’s going on with `send`.
