### ISSUE TITLE
Audit the haddocks for warnings and coverage

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#246]
For 1.0 I’d like to make sure that we audit the docs for warnings, coverage, etc.

After 1.0, I’d like to make sure we check the above in CI.

**Comment by patrickt** [comment]
This is a noble goal, but `cabal haddock` is _very_ noisy, and complains about lack of documentation on things that, in context, don’t really need any docs. Let’s think on this.

**Comment by robrix** [comment]
By “audit” I mean “go through and make sure we’re ok with” not “ensure the complete absence of” any warnings. (The latter will be trickier to enforce in CI, of course.)
