### ISSUE TITLE
Reintroduce & deprecate Control.Effect.Carrier module

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#248]
We should reintroduce `Control.Effect.Carrier` as a deprecated module re-exporting `Control.Carrier`.

**Comment by patrickt** [comment]
I feel like since 1.0 is such a big reorg, we could get away with eliding the deprecation?

**Comment by robrix** [comment]
Good point. I think it’d make porting stuff like `semantic` a little easier to have this, but once you’re done, you’re done, so I’m not sure it’s worth the effort?

**Comment by robrix** [comment]
Yeah, not really worth it.
