### ISSUE TITLE
Alternative, MonadPlus, MonadFail, and MonadIO constraints are inconsistent with the rest of the library

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#260]
We support `Alternative` & `MonadPlus` as interfaces to `NonDet` carriers, `Fail.MonadFail` as an interface to `Fail` (itself a synonym for `Throw String`), and `MonadIO` as an interface to `Lift IO` (actually `MonadIO m => Lift m`).

This results in weirdly inconsistent usage: e.g. `Alternative m` constraints instead of `Has NonDet sig m`, and also means that we can’t easily use stuff built against `Choose` in stuff built against `Alternative` without incurring redundant constraints.

In #82 we opted to resolve that by making `MonadIO` the authoritative interface, obviating the need for `Lift IO` constraints, but that approach won’t work nicely for `Choose` vs. `Alternative` because the whole point of `Choose` is that some of its carriers can’t have `Alternative` instances.

**Comment by robrix** [comment]
I kind of feel like we should go all-in on `Has` constraints for the nondeterminism stuff, and provide a bridging `newtype` which can be added into the mix as desired:

```haskell
newtype ViaNonDet m a = ViaNonDet { runViaNonDet :: m a }

instance Has NonDet sig m => Alternative (ViaNonDet m) where
  empty = NonDet.empty
  (<|>) = (NonDet.<|>)
```

(We could also call this `ViaEffect` and have it do double duty for e.g. `MonadFail`.)

Then, as a plus, we could 🔥 the `Alternative` & `MonadPlus` (& `MonadFail`, …) instances from all the carriers (cf #215). Note that `MonadIO` would require something analogous to `Has`, but with a fundep to ensure that we can still have `MonadIO m => Lift m` determine a `MonadIO` instance, instead of only `Lift IO` (cf #98); we can call this `HasLast` or something. (IIRC `freer-simple` did something like this.)

**Comment by patrickt** [comment]
FWIW, I don’t object to the current approach of using `Alternative` to interact with `Choose :+: Empty` and providing equivalents of `<|>` and `empty` in the `Choose` and `Empty` effects themselves. I think most people porting existing nondeterminism code are going to use an `Alternative` interface, and when I write new nondet code I personally think in terms of `Alternative`. Having a special newtype for these instances strikes me as more warty than the current approach.

**Comment by robrix** [comment]
Yeah, that’s fair. Closing.
