### ISSUE TITLE
Change :+: to just +?

### ISSUE THREAD

**Issue by ocharles** [fused-effects/fused-effects#319]
I believe GHC will let you just write `+` as the type constructor for sum, which IMO is much tidier. They downside is a clash with + for type level natural numbers, but that can always be fixed with qualified imports. Any thoughts?

**Comment by robrix** [comment]
Definitely tidier, but (IMO) obscures the fact that we’re talking about a datatype. And given that one pretty much just writes it in `Algebra` instances, I’m not finding its tidiness very compelling. Or are there other cases I’m missing where you’d like to be able to abbreviate this?

**Comment by ocharles** [comment]
Personally the fact that it's surrounded by `:` doesn't make it much clearer it's data to me, so I'm not so convinced. The fact that `:` has meaning is afaik historic and somewhat Haskell folklore. But yes, tidying up Algebra us exactly what I'm interested in

**Comment by robrix** [comment]
@ocharles: It’s definitely not just historic; `:` is reserved for data constructors (in value-level positions).

The convention when used as a type operator is pretty well established by e.g. `GHC.Generics`. Given that, the ambiguity (both for the renamer and the reader), and how marginal the improvement would actually be, I’m not keen on renaming this.

Nonetheless, thanks for the suggestion!
