### ISSUE TITLE
 Bump base bound for fused-effects 0.1.2.1

### ISSUE THREAD

**Issue by athas** [fused-effects/fused-effects#336]
I would like to have the `base` <4.13 bound on [fused-effects-0.1.2.1](http://hackage.haskell.org/package/fused-effects-0.1.2.1) bumped to <4.14 with a Hackage revision.  I have verified that `fused-effects-0.1.2.1` works with this version of `base`. While this version of `fused-effects` is a year old and newer versions don't have this restrictive bound, I'm looking to compile a program ([komposition](https://github.com/owickstrom/komposition)) that does not work with newer versions of `fused-effects`, and where updating is nontrivial.

**Comment by patrickt** [comment]
That seems like a reasonable request, if @robrix agrees—I don’t think we have many clients of that version anymore, and Komposition is one of our bigger users, so I don’t see the harm in keeping it compiling.

**Comment by robrix** [comment]
No objection 👍

**Comment by patrickt** [comment]
Published. Let us know if you need anything else, @athas, especially if you plan to update.
