### ISSUE TITLE
PrimMonad instances?

### ISSUE THREAD

**Issue by patrickt** [fused-effects/fused-effects#337]
The [`primitive`](http://hackage.haskell.org/package/primitive-0.7.0.0) package provides support for lifting operations on ST and IO primitives into a parent monad using the `PrimMonad` typeclass and `PrimState` associated type. Every monad transformer is trivially an instance of `PrimState`.

`primitive` has a small dependency footprint (it adds nothing we’re not already using), is widely used (the reverse deps engine says it has 356 direct dependencies, and even more indirect given `vector`’s dependency on it), and enables the use of the generic [`Vector`](https://hackage.haskell.org/package/vector-0.12.0.3/docs/Data-Vector-Generic.html) interface. I propose adding these trivial `PrimMonad` instances to the hierarchy of carrier monads.

The only strike against this is dependency footprint, I feel. Normally, I would say “just use the types from `mtl`”, but even if we were to stick to `transformers`-based stacks, an instance `PrimMonad a => PrimMonad (Lift IO)` becomes necessary. 

I’m interested in anyone’s thoughts on this. I’m currently working around this in `fused-effects-mwc-random` by defining a bunch of orphan instances—and maybe such a module is preferable to introducing this that and the other into `fused-effects` core. Thoughts?

**Comment by robrix** [comment]
I’m not sure I really understand the use cases for `primitive`. What will we be enabling by supporting it? Who will use it?

> Normally, I would say “just use the types from `mtl`”, but even if we were to stick to `transformers`-based stacks, an instance `PrimMonad a => PrimMonad (Lift IO)` becomes necessary.

I don’t understand this proposed instance. Why would we need an instance for the `Lift` _effect_? What is `a` here? `IO` has an `Algebra` instance and so we don’t need to wrap it in `LiftC` any more, so I don’t follow why this would require any support from us?

**Comment by patrickt** [comment]
I forgot about the fact that `IO` has an Algebra instance! That indeed fixes my problem. Never mind!
