### ISSUE TITLE
Add IORef carrier for State?

### ISSUE THREAD

**Issue by patrickt** [fused-effects/fused-effects#338]
We have one of these in `fused-effects-exceptions`. Judging by the amount of times that @robrix is using it, it seems generally useful.

**Comment by robrix** [comment]
I’d like to let it percolate a little longer. I’m not actually using it very much.

**Comment by patrickt** [comment]
Will be fixed with https://github.com/fused-effects/fused-effects/pull/422.

**Comment by robrix** [comment]
Fixed with #422.
