### ISSUE TITLE
Add Algebra instance for Ap.

### ISSUE THREAD

**Issue by patrickt** [fused-effects/fused-effects#342]
As @robrix points out, Ap is the identity monad transformer, so we can define a passthrough instance and allow standard effect invocation inside code like this:
```haskell
foo :: Has Blah sig m => Ap m ()
```

**Comment by robrix** [comment]
Better yet, you wouldn’t even have to mention `Ap` in the types to use it:

```haskell
doThings :: [Thing] -> m ()
doThings = getAp . foldMap action

action :: Has Stuff sig m => Thing -> m ()
action thing = do
  stuff thing
```
