### ISSUE TITLE
Effect requests should be inlinable

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#345]
These are tiny, and _not_ inlining them hurts—@tclem & I ran into a nasty example the other day where `ask` of all things was responsible for a measurable chunk of runtime.

I’m not sure yet if we should do `INLINE` or `INLINABLE` but I would suggest starting with the latter and measuring.

**Comment by patrickt** [comment]
We already do it for most of the effect requests. I have no idea why `Reader` was omitted.

If memory serves, `INLINE` does a better job, but my memory is no substitute for a benchmark 👍

**Comment by robrix** [comment]
Oh, we do? That’s great!
