### ISSUE TITLE
Define `state` for State effects

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#348]
```haskell
state :: Has (State s) sig m => (s -> (s, a)) -> m a
```

is sometimes handy.

**Comment by patrickt** [comment]
I liked omitting this, primarily because `state` is such a useful variable name that it seems a shame to reserve this with what is a very niche function.

**Comment by patrickt** [comment]
But I have hand-rolled a similar function in the past, so perhaps I’m being hypocritical.

**Comment by robrix** [comment]
> I liked omitting this, primarily because `state` is such a useful variable name that it seems a shame to reserve this with what is a very niche function.

1. I don’t think we should think of this as reserving the name; Haskell makes it very easy to import, hide, and qualify specific symbols, so IMO this is an unnecessarily conservative framing.

2. Niche or not, it’s pretty much standard, and very much in use, so we’re making it unnecessarily difficult for those projects to use `fused-effects` instead.

On the other hand, I also compile with `-Wno-name-shadowing` everywhere, which means I’m somewhat insulated from the effects of the change. I’d appreciate feedback from users, especially anybody who uses `-Wname-shadowing` routinely.

**Comment by ocharles** [comment]
I've also toyed with using `liftState :: MonadState m => State s a -> m a` in the past here. Not sure if that would really work in `fused-effects`, but just throwing that out there!

**Comment by robrix** [comment]
@ocharles oh, nice! That deserves some experimentation in `diffused-effects` at the least.
