### ISSUE TITLE
Cache on GitHub Actions for `fused-effects` is not working

### ISSUE THREAD

**Issue by chshersh** [fused-effects/fused-effects#349]
I was lurking into GitHub Actions cache configurations for Haskell. `fused-effects` contains many dependencies, so I expect that having cache on CI configured is essential. I see that `actions/cache` is used in this repository. However, it doesn't look like the cache is working. Looking at [one of the recent builds](https://github.com/fused-effects/fused-effects/runs/399340695) I see that the job spent ~5minutes on installing dependencies which usually shouldn't happen. But it happens consistently, and from the logs, I see that each CI job builds all dependencies from scratch each time.

I was wondering, is it possible to patch configuration in some way so that cache visible for CI? Waiting for 5 minutes might not be that critical for now, but I have packages with a lot of dependencies, and I'd love to know why this is happening. Thanks for the reply!

**Comment by robrix** [comment]
@chshersh: I’d recommend asking this in https://github.community; I’m not able to support GitHub Actions and given that, as you note, our cache isn’t working, I’m probably not the best person to ask anyway 😅

We are using the old preview version of that action and should update, tho, possibly that is a factor here. I do recall it was working at some point.

**Comment by chshersh** [comment]
@robrix No worries, I will ask there :slightly_smiling_face: I just thought that maybe you have some insight on what's going on. But I'll address my issue upstream :+1:

**Comment by robrix** [comment]
Nope, no insight other than the version thing (which does look to have resolved things in #351, so there’s that at least).
