### ISSUE TITLE
Lifting MonadCatch into a fused-effects effect

### ISSUE THREAD

**Issue by AlistairB** [fused-effects/fused-effects#356]
Hi,

I have a problem I am failing to solve where I have some result `MonadIO m, MonadCatch m` in my carrier `Algebra` instance. I want to discharge / lift the `MonadCatch m` bit into either a `Catch` effect, or alternatively into a `Lift IO` (and another carrier would handle IO exceptions later on).

Here is some code..

```haskell
newtype ReaderGoogleEnvGoogleIOC (s :: [Symbol]) m a = ReaderGoogleEnvGoogleIOC {runReaderGoogleEnvGoogleIOC :: m a}
  deriving (Functor, Applicative, Monad, MonadIO)

instance (Algebra sig m, MonadIO m, Has (Lift IO) sig m, Has (Error Text) sig m, G.AllowScopes s) => Algebra (Reader (G.Env s) :+: sig) (ReaderGoogleEnvGoogleIOC s m) where
  alg (L (Ask r2mk)) = ReaderGoogleEnvGoogleIOC env2 >>= r2mk
    where
      -- Naively this is what gogol produces when creating an `Env`. Fails with `Cannot deduce MonadCatch m at ReaderGoogleEnvGoogleIOC env`
      env :: (MonadIO m, MC.MonadCatch m, G.AllowScopes s) => m (G.Env s)
      env = do
        lgr <- G.newLogger G.Debug stdout
        env <- G.newEnv <&> (G.envLogger .~ lgr) . (G.envScopes .~ Proxy)
        pure env

      -- this is me failing to convert / lift the MonadCatch into a fused effects effect
      env2 :: (Has (Lift IO) sig m, Has (Error Text) sig m, G.AllowScopes s) => m (G.Env s)
      env2 = do
        lgr <- G.newLogger G.Debug stdout
        env <- G.newEnv <&> (G.envLogger .~ lgr) . (G.envScopes .~ Proxy)
        -- the catch is from fused-effects-exceptions, however I don't have an Exception as such, I have a `MonadCatch m`
        -- nor does catch from exceptions package allow me to change the m type it seems
        MC.catch (pure env) exceptionToFusedError
  alg (R other) = ReaderGoogleEnvGoogleIOC (alg (handleCoercible other))


exceptionToFusedError ::
  ( Exception e,
    Has (Error Text) sig m
  ) => e -> m a
exceptionToFusedError _ = throwError @Text "Google boom"
```

MonadUnliftIO seems like it would help, but I think `liftWith` is the way to do this with fused-effects, but I can't quite solve how to use it. I guess the key problem is:

1. I only have `MonadIO m` not `IO` so cannot use `liftIO` and go from there.
2. I can't see anyway to discharge the MonadCatch m constraint. Eg. if I could convert it to some `m (Either Boom a)` then I think I would be able to wire it up as a `Catch Boom` effect.

Any tips on a way forward?

(Let me know if there is a better place for my noob questions ;))

**Comment by robrix** [comment]
I’m not immediately familiar with `MonadCatch`; what package does it come from?

Also, no worries, this is exactly the right place 👍

**Comment by ocharles** [comment]
It comes from the exceptions library, it's fairly widely used these days

**Comment by AlistairB** [comment]
So at least the `amazonka` + `gogol` packages use `MonadCatch` to represent errors in setting up the cloud environment `Env` which includes auth and other bits.

http://hackage.haskell.org/package/amazonka-1.6.1/docs/Network-AWS-Env.html#v:newEnv
https://hackage.haskell.org/package/gogol-0.5.0/docs/Network-Google.html#v:newEnv

As mentioned `MonadCatch` is from `exceptions` https://hackage.haskell.org/package/exceptions-0.10.4/docs/Control-Monad-Catch.html#t:MonadCatch

**Comment by AlistairB** [comment]
Ok.. I figured out what I can do.. which is simply specialize the type to `IO`, which means I can use `liftIO` and everything works.

```haskell
instance (Algebra sig m, MonadIO m, Has (Error Text) sig m, G.AllowScopes s) => Algebra (Reader (G.Env s) :+: sig) (ReaderGoogleEnvGoogleIOC s m) where
  alg (L (Ask r2mk)) = liftIO env >>= r2mk
    where
      -- (MonadIO m, MC.MonadCatch m, G.AllowScopes s) => m (G.Env s) can simply be specialised to IO (G.Env s)
      env :: IO (G.Env s)
      env = do
        lgr <- G.newLogger G.Debug stdout
        env <- G.newEnv <&> (G.envLogger .~ lgr) . (G.envScopes .~ Proxy)
        pure env
  alg (R other) = ReaderGoogleEnvGoogleIOC (alg (handleCoercible other))
```

Also, I had planned to heavily use `Reader Blah` to load in all the setup bits, however I now realize that approach is tricky to integrate with servant. Servant wants a `YourMonadStack a -> Handler a` function and I get issues if I include layers in `YourMonadStack` that are setup bits the handlers don't know about. So I will move the building of the startup deps into main for now at least.

**Comment by AlistairB** [comment]
Also...

I've realised `YourMonadStack a -> Handler a` explanation is totally incorrect. I can do a series of `Reader Blah` to load various dependencies. I was just misunderstanding what order I should be running my effects in. eg. I was doing `runReaderGoogleEnv` as the first step with the thinking `I want the google env to be available in the subsequent effects!`. However of course, it is the opposite. I need the `Reader GoogleEnv` to still be in the effect stack when running things like `WriteToGooglePubSub`, so the `Reader GoogleEnv` needs to be towards the end.

Ie. this order makes it all work beautifully yay.

```haskell
  app
    & runQueueEventPublishGooglePubSubIOC
    & runReaderGoogleEnvGoogleIOC
    & runReader @Config config
    & runError @AppError
    & runAppEventEmitStdoutIOC
```
