### ISSUE TITLE
Help writing `Algebra` instance for "composed effect"

### ISSUE THREAD

**Issue by evanrelf** [fused-effects/fused-effects#380]
Hi there! I'm trying to write my first non-trivial effect (i.e. not just reinterpreting an effect into an IO function), a port of Matt Parsons' amusingly-named [`garlic-bread`](https://github.com/parsonsmatt/garlic-bread) library, but I'm having trouble writing the `Algebra` instance for my carrier monad.

If GitHub issues aren't a good place for this kind of question, please feel free to close this issue. Otherwise, I'd really appreciate some pointers!

The effect is incredibly simple – just the composition of the `Reader` and `Error` effects – and defining it in `fused-effects` is pretty straightforward:

```haskell
type Bread crumb exit = Reader [crumb] :+: Error ([crumb], exit)

withCrumb :: Has (Bread crumb exit) sig m => crumb -> m a -> m a
withCrumb crumb = local (crumb :)

exit :: forall crumb exit sig m a. Has (Bread crumb exit) sig m => exit -> m a
exit e = crumbs @_ @exit >>= \cs -> throwError @([crumb], _) (cs, e)

handleExit
  :: forall crumb exit sig m a. Has (Bread crumb exit) sig m
  => m a -> (exit -> m a) -> m a
handleExit action handler = catchError @([crumb], _) action (handler . snd)

crumbs :: Has (Bread crumb exit) sig m => m [crumb]
crumbs = ask
```

I'm trying to leverage the existing effects as much as possible, so I've defined my carrier monad and its run function like so:

```haskell
runBread :: BreadC crumb exit m a -> m (Either ([crumb], exit) a)
runBread = runError . runReader [] . runBreadC

newtype BreadC crumb exit m a
  = BreadC { runBreadC :: ReaderC [crumb] (ErrorC ([crumb], exit) m) a }
```

My problem is with writing the `Algebra` instance for my carrier monad. I don't understand how `Algebra` works very well. So far I've been able to implement basic stuff by copying examples, but I haven't done anything sophisticated.

I've been looking at examples from `fused-effects` and its companion libraries, but I haven't found any good examples of writing `Algebra` instances for "composed effects". I believe there's only two "composed effects" in `fused-effects` right now – `NonDet` and `Error` – but neither is a very good, general example. `NonDet`'s instance is really complicated, and `Error` cheats by deferring to `ExceptT`.

This is what I have so far (lol not much...), which typechecks but may be totally wrong:

```haskell
instance (Algebra sig m, Effect sig)
  => Algebra (Bread crumb exit :+: sig) (BreadC crumb exit m) where
  alg (R other) = BreadC (send (handleCoercible other))
  alg (L effect) = case effect of
    L readerEffect -> BreadC (send (handleCoercible readerEffect))
    R errorEffect -> undefined
```

My work so far is [available here](https://github.com/evanrelf/fused-effects-garlic-bread), but I think I've included code snippets for everything relevant.

**Comment by evanrelf** [comment]
I'm realizing I may also need to change the type of the effect:

```diff
-type Bread crumb exit = Reader [crumb] :+: Error exit
+type Bread crumb exit = Reader [crumb] :+: Error ([crumb], exit)
```

**Comment by cnr** [comment]
I'm sure someone else can better explain the intuition than I can, but an (the?) Algebra instance:
```hs
instance (Algebra sig m, Effect sig) => Algebra (Bread crumb exit :+: sig) (BreadC crumb exit m) where
    alg (L (L reader)) = BreadC (alg (L (handleCoercible reader)))
    alg (L (R err)) = BreadC (alg (R (L (handleCoercible err))))
    alg (R other) = BreadC (alg (R (R (handleCoercible other))))
```
you're essentially reassociating the `(Reader :+: Error) :+: sig` into `Reader :+: (Error :+: sig)`

---

Another approach to "composed effects" is to define a bespoke effect, e.g.,
```hs
data Bread crumb exit m k
  = forall a. WithCrumb crumb (m a) (a -> m k)
  | Exit exit (m k)
  | ...
```
which simplifies defining the algebra instance (you only have to deal with a single `L`/`R`), at the cost of complex HFunctor/Effect instances --
```hs
instance Algebra sig m => Algebra (Bread crumb exit :+: sig) (BreadC crumb exit m) where
  alg (L (WithCrumb ...)) = BreadC (local ...)
  ...
  -- one 'R' on the right-hand side for each of the "inner" carriers, ReaderC and ErrorC
  alg (R other) = BreadC (alg (R (R (handleCoercible other))))
```

maybe not a good fit for this effect in particular, but something to keep in mind

---

one downside of using this effect: you're going to have to use type applications at essentially every callsite of exit/withCrumb/etc. perhaps the `Labelled` machinery could help?

**Comment by evanrelf** [comment]
Thanks, @cnr!

> you're essentially reassociating the `(Reader :+: Error) :+: sig` into `Reader :+: (Error :+: sig)` (the signature carried by the inner carriers)

I see what you mean; thinking about it that way helps. Though it doesn't come to me intuitively.

> at the cost of complex HFunctor/Effect instances

Yeah for this effect I'd rather stick to composing other effects, but point taken.

> one downside of using this effect: you're going to have to use type applications at essentially every callsite of exit/withCrumb/etc. perhaps the Labelled machinery could help?

Yeah you're right. That's a bummer. I'll look into `Labelled`.

**Comment by evanrelf** [comment]
It's pretty bad ☹️

```haskell
newtype Crumb = Crumb String
newtype Exit = Exit String

program :: Has (Bread Crumb Exit) sig m => m ()
program = do
  ys <- withCrumb @_ @Exit (Crumb "1") $ do
    pure $ do
      let xs = [1 .. 5]
      x <- xs
      pure (x * 2)
  cs <- crumbs @Crumb @Exit
  if (null cs || null ys) then do
    exit @Crumb (Exit "uh oh")
  else
    pure ()

```

I think the only options we have to improve type inference are:

- `FunctionalDependencies`: I'm not creating a typeclass, and this would restrict how many `Bread` effects you could have
- `TypeFamilyDependencies`: Same story as above, except with type families
- `QuantifiedConstraints`: I tried stuff like this but it kept saying that `sig` was ambiguous, and I can't seem to use type applications to fill in `sig`:

    ```haskell
    crumbs
      :: forall crumb sig m. (forall exit. Has (Bread crumb exit) sig m)
      => m [crumb]
    crumbs = ask
    ```

    ```
    src/Control/Effect/Bread.hs:52:10-12: error:
        • Could not deduce (Control.Effect.Sum.Member
                              (Reader [crumb]) sig0)
            arising from a use of ‘ask’
          from the context: forall exit. Has (Bread crumb exit) sig m
            bound by the type signature for:
                       crumbs :: forall crumb (sig :: (* -> *) -> * -> *) (m :: * -> *).
                                 (forall exit. Has (Bread crumb exit) sig m) =>
                                 m [crumb]
            at src/Control/Effect/Bread.hs:(49,1)-(51,14)
          The type variable ‘sig0’ is ambiguous
    ```

**Comment by evanrelf** [comment]
It looks like I can't easily label my effect as its implemented right now, due to [this comment in the docs for `HasLabelled`](https://hackage.haskell.org/package/fused-effects-1.0.2.0/docs/Control-Effect-Labelled.html#t:HasLabelled):

> Note that if `eff` is a sum, it will _not_ be decomposed into multiple `LabelledMember` constraints. While this technically is possible, it results in unsolvable constraints, as the functional dependencies in `Labelled` prevent assocating the same label with multiple distinct effects within a signature.

Oh well.

**Comment by cnr** [comment]
It seems like [I unwittingly reinvented a similar solution](https://github.com/fossas/spectrometer/blob/master/src/Parse/XML.hs#L153) in our XML-parsing code, and I think that approach could be improved:

We're essentially using `Reader ParsePath :+: Error ParseError`, and embedding the `ParsePath` in the `ParseError` when a failure happens. The approach of embedding the "crumbs" in the error type -- and weakening constraints on everything but `exit` -- could work out for better type inference:

```hs
type Bread crumb exit = Reader [crumb] :+: Error exit

withCrumb :: Has (Reader [crumb]) sig m => crumb -> m a -> m a
withCrumb crumb = local (crumb :)

exit :: Has (Bread crumb exit) sig m => ([crumb] -> exit) -> m a
exit f = crumbs >>= \cs -> throwError (f cs)

handleExit :: Has (Error exit) sig m => m a -> (exit -> m a) -> m a
handleExit = catchError

crumbs :: Has (Reader [crumb]) sig m => m [crumb]
crumbs = ask

runBread :: BreadC crumb exit m a -> m (Either exit a)
runBread = runError . runReader [] . runBreadC

newtype BreadC crumb exit m a
  = BreadC { runBreadC :: ReaderC [crumb] (ErrorC exit m) a }
  deriving (Functor, Applicative, Monad)
```

If we add `[Crumb]` as the last field on `Exit`:
```hs
data Crumb = Crumb String
data Exit = Exit String [Crumb]
```

we get pretty good type inference (your example from before):
```hs
program :: Has (Bread Crumb Exit) sig m => m ()
program = do
  ys <- withCrumb (Crumb "1") $ do
    pure $ do
      let xs = [1 .. 5]
      x <- xs
      pure (x * 2)
  cs <- crumbs @Crumb
  if (null cs || null ys) then do
    exit (Exit "uh oh")
  else
    pure ()
```

**Comment by patrickt** [comment]
@cnr That's a really interesting solution!

**Comment by evanrelf** [comment]
I think I invented a new solution to these type inference issues. It isn't as nice as just plain functions, but I think it might be better than labels:

```haskell
type Bread crumb exit = Reader [crumb] :+: Error ([crumb], exit)


data BreadFns crumb exit sig m = Has (Bread crumb exit) sig m => BreadFns
  { withCrumb :: forall a. crumb -> m a -> m a
  , exit :: forall a. exit -> m a
  , handleExit :: forall a. m a -> (exit -> m a) -> m a
  , crumbs :: m [crumb]
  }


useBread
  :: forall crumb exit sig m. Has (Bread crumb exit) sig m
  => m (BreadFns crumb exit sig m)
useBread = pure BreadFns{..} where
  withCrumb :: crumb -> m a -> m a
  withCrumb crumb = local (crumb :)

  exit :: exit -> m a
  exit e = crumbs >>= \cs -> throwError @([crumb], _) (cs, e)

  handleExit :: m a -> (exit -> m a) -> m a
  handleExit action handler = catchError @([crumb], _) action (handler . snd)

  crumbs :: m [crumb]
  crumbs = ask
```

It's inspired by Thomas Honeyman's port of React Hooks to PureScript's Halogen UI library, called [`halogen-hooks`](https://github.com/thomashoneyman/purescript-halogen-hooks/). React/Halogen uses a `useEffect` function that returns a product type with the things you need to use the effect.

This seems to work without issue in `fused-effects` (though I haven't tested with the more exotic effects with lots of existential quantification and stuff), and isolates the bad type inference to one place, the `use*` function.

Here's a messy example program that typechecks. Pay attention to the `useBread` function. With only one `Bread` effect in the type signature, this requires no type annotations. Once I added the second `Bread` effect, I had to add the type annotations. Also note that if you're using more than one of the same effect in the same function, you have to rename things to avoid conflicts.

```haskell
newtype Crumb = Crumb String
newtype Exit = Exit String

newtype Crumb1 = Crumb1 String
newtype Exit1 = Exit1 String

program :: Has (Bread Crumb Exit) sig m => Has (Bread Crumb1 Exit1) sig m => m ()
program = do
  BreadFns{..} <- useBread @Crumb @Exit
  BreadFns{crumbs = crumbs1} <- useBread @Crumb1 @Exit1
  ys <- withCrumb (Crumb "1") $ do
    pure $ do
      let xs = [1 .. 5]
      x <- xs
      pure (x * 2)
  cs <- crumbs
  cs1 <- crumbs1
  if (null cs || null ys || null cs1) then do
    exit (Exit "uh oh")
  else
    pure ()
```
