### ISSUE TITLE
Add Accum effect

### ISSUE THREAD

**Issue by turion** [fused-effects/fused-effects#389]
It would be nice if there were an effect corresponding to `AccumT`. (See e.g. http://hackage.haskell.org/package/transformers-0.5.6.2/docs/Control-Monad-Trans-Accum.html) It's more powerful than `Writer` since it's possible to read the current state, but more specific than `State` because its internal state is a monoid.

If you want I can contribute this as a PR.

**Comment by joshvera** [comment]
That sounds excellent. An `Accum` effect would be most welcome!

**Comment by turion** [comment]
Great, I'll start hacking :) should it be the `StateC` carrier?

**Comment by turion** [comment]
Ah, I'm just realizing that e.g. `Writer` has lots of different carriers. I guess all of those are suitable for `Accum` as well.

**Comment by robrix** [comment]
This was closed by #391.
