### ISSUE TITLE
Regression with Error in fused effects 1.1

### ISSUE THREAD

**Issue by AlistairB** [fused-effects/fused-effects#397]
Hi :wave: 

I'm seeing a regression after upgrading to fused effects 1.1 with my carrier for `Error`. I have `EmitErrorsC` whose job it is to log any errors (emitting to a different effect) and unwrapping to a concrete `ErrorC`. In 1.0.2.2 it works fine, however in 1.1 this is now getting suck in an infinite loop.

I created a repro here https://github.com/AlistairB/fused-simple-repro/pull/1 . `master` is on 1.0.2.2 and tests pass. The PR updates to 1.1 and the second test gets stuck forever. (Run with `stack test`)

The issue seems to be the interaction of the two effects somehow. If I remove the `AppEventEmit` effect entirely `EmitErrorsC` then works as expected.

Am I doing something silly, or is this a bug?

**Comment by robrix** [comment]
[It’s the `R other` case](https://github.com/AlistairB/fused-simple-repro/pull/1/files#diff-1893f7697c1647489de7d9cf8917f9c0R34). You’re calling that in `EmitErrorsC`, and so it’s calling into itself recursively, infinitely.

Incidentally, you can defer the implementations of the other two cases to `ErrorC` pretty easily, which will save a lot of boilerplate, using much the same means as for the `R other` case. That will still allow you to emit the `boom` event on the throw case, too.

**Comment by robrix** [comment]
(Gonna go ahead and close this, but feel free to reopen if e.g. I’ve misidentified it.)

**Comment by AlistairB** [comment]
Thanks @robrix . As expected I was misunderstanding :sweat_smile: 

I've sort of adapted from the implementation of `ExceptT` which works :smiley: 

```haskell
    (R other) ->
      EmitErrorsC $
        ErrorC $
          ExceptT $
            thread (either (pure . Left) runCatchE ~<~ hdl) other (Right ctx)

runCatchE ::
     EmitErrorsC e m a
  ->  m (Either e a)
runCatchE =
  runError . runEmitErrorsC
```

> Incidentally, you can defer the implementations of the other two cases to ErrorC pretty easily, which will save a lot of boilerplate, using much the same means as for the R other case. That will still allow you to emit the boom event on the throw case, too.

Do you mind giving an example of how I can do this? I'm afraid I can't quite figure it out (either for `(L (R (Catch m h)))` or `(R other)`). For `(R other)`, I'm trying things like `EmitErrorsC $ alg (runEmitErrorsC . hdl) other ctx`, but this isn't quite right.

**Comment by AlistairB** [comment]
Ah hmm. Perhaps like this?

```haskell
instance (Algebra sig m, Has AppEventEmit sig m) => Algebra (Error e :+: sig) (EmitErrorsC e m) where
  alg hdl sig ctx = case sig of
    (L (L (Throw e))) -> do
      emitAppEvent "boom"
      EmitErrorsC $ alg (runEmitErrorsC . hdl) sig ctx
    _ -> EmitErrorsC $ alg (runEmitErrorsC . hdl) sig ctx
```

**Comment by robrix** [comment]
I think that should do it, yes.

**Comment by AlistairB** [comment]
Thanks for your help! :heart:

**Comment by robrix** [comment]
You’re very welcome!
