### ISSUE TITLE
Carriers should preserve MonadResource

### ISSUE THREAD

**Issue by ProofOfKeags** [fused-effects/fused-effects#398]
Currently there appears to be many `MonadIO` preservation instances

```haskell
instance MonadIO m => MonadIO (SomeCarrierC m) where
```

but none for `MonadResource`. Since The resource effect was actually deprecated in this package, I'm not sure how else I am to integrate with libs that require MonadResource (such as `streaming-bytestring` which hold onto handles).

Perhaps more generally, I'd like to know what the "correct" way to use fused-effects when I also have to do resource management.

**Comment by robrix** [comment]
I’ll try to give this a closer look soon, but in the meantime you can always use the monad transformers from `transformers`—we’ve defined `Algebra` instances for (last I checked) all of them (except `ListT`).

**Comment by robrix** [comment]
(Side note: `MonadIO` is in base; `MonadResource` is not. I’m reluctant to add dependencies if we don’t have to.)

**Comment by patrickt** [comment]
I agree with @robrix: the correct thing here is to use transformers from `carriers`. A dependency on `resourcet` is not the right direction for us.

> Perhaps more generally, I'd like to know what the "correct" way to use fused-effects when I also have to do resource management.

I recommend using the lifted `bracket` in https://github.com/fused-effects/fused-effects-exceptions.
