### ISSUE TITLE
Update dependency bounds to support GHC 9.8

### ISSUE THREAD

**Issue by JakobBruenker** [fused-effects/fused-effects#451]
As far as I can tell, everything, including the test suite, still works, if the bound for `base` is updated from `< 4.19` to `< 4.20`, and the bound for `hedgehog` is updated from `< 1.3` to `< 1.5`.

This would allow `fused-effects` to support GHC 9.8.

A caveat is that there are some additional warnings during compilation regarding `-Wmissing-role-annotations` and `-Wterm-variable-capture`.

**Comment by robrix** [comment]
We'll want to either placate the compiler or disable the warnings (as we've done for other versions), but otherwise 👍 from me. I'll get to this myself eventually if no one beats me to it.

**Comment by aavogt** [comment]
In the meantime I put this in `cabal.project`
```
packages: .
allow-newer: fused-effects:base
```
