### ISSUE TITLE
First-order effects admit an automatic definition of handle

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#54]
To wit, `handle state handler = coerce . fmap (handler . (<$ state))`.

We should use this in the README for `Teletype`.

**Comment by mitchellwrosen** [comment]
This is possible to derive with `DerivingVia`:

```haskell
newtype FirstOrderEffect
          (sig :: (Type -> Type) -> Type -> Type)
          (m :: Type -> Type)
          (k :: Type)
  = FirstOrderEffect (sig m k)
  deriving stock Functor

instance
     ( forall m. Functor (sig m)
     , HFunctor sig
     )
  => HFunctor (FirstOrderEffect sig) where

  hmap f (FirstOrderEffect m) =
    FirstOrderEffect (hmap f m)

instance
     ( forall m n a. Coercible (sig m a) (sig n a)
     , forall m. Functor (sig m)
     , Effect sig
     )
  => Effect (FirstOrderEffect sig) where

  handle state handler =
    coerce . fmap (handler . (<$ state))
```

**Comment by mitchellwrosen** [comment]
```haskell
data MyEffect a b c m k = ...
  deriving HFunctor via (FirstOrderEffect (MyEffect a b c))
```

**Comment by mitchellwrosen** [comment]
Whoops, ignore that, it's just an infinite loop... :sweat_smile:

**Comment by robrix** [comment]
Nice one! Unfortunately, the dependency on `-XDerivingVia` and `-XQuantifiedConstraints` puts it out of reach of some of our supported versions of `ghc` for a while. (Tho we could always use `-XCPP` or w/e to do this conditionally in 8.6+.)

Seems like we could also do this with `DefaultSignatures`, tho that would probably require `-XQuantifiedConstraints` too.
