### ISSUE TITLE
Logical cull operator

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#68]
Picking up from @zenzike’s suggestion
(https://github.com/robrix/fused-effects/issues/65#issuecomment-435676919), `Cut` offers `call` and `cut`, but we can also express `cull` as a scoped effect to select only the first child in p.

I think this is the same as the `once` operator described in _Backtracking, Interleaving, and Terminating Monad Transformers_, for pruning or “don’t-care nondeterminism.”

**Comment by zenzike** [comment]
Yes, it’s exactly that. Also in the syntax and semantics for operations with scope paper

**Comment by robrix** [comment]
Oh that’s right! I forgot that.

We’ve got an effect handler for `NonDet`, `runNonDetOnce`, that does this globally. I think we could define this as a scoped effect, either as part of `Cut` or as a separate effect working with `NonDet` like `Cut` does. I’m kind of leaning towards `Cut` at the moment, but I’m not married to the idea.
