### ISSUE TITLE
Document reinterpreting effect handlers

### ISSUE THREAD

**Issue by robrix** [fused-effects/fused-effects#9]
It’s possible to reinterpret an effect into some other effect, essentially replacing it with one (or more) effects in the signature. Document this.

**Comment by robrix** [comment]
I think this would warrant having an example written up around it.

**Comment by iand675** [comment]
Hi, I'd like to write a bit about this, any thoughts on which part of the docs it would be best to put it in?

**Comment by patrickt** [comment]
I’d say it merits its own `.md` file in `docs/`. `reinterpreting_effects.md` or something.

**Comment by robrix** [comment]
and/or something in the examples? not sure that the extant reinterpret log example is super elucidating

**Comment by robrix** [comment]
Closed by @iand675 in #297.
